### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by adityadeshpande09** [kkrypt0nn/wordlists#45]
Add License for the project.
Can I work on the same ?

**Comment by kkrypt0nn** [comment]
There's no need for a license, it's free to use for whatever you need

**Comment by adityadeshpande09** [comment]
> There's no need for a license, it's free to use for whatever you need

ohk , the license generally permits for free usage as well, it is generally considered a good practice to have a license

**Comment by kkrypt0nn** [comment]
I know, though here it's not needed at all - they're just files with a list of words where there is no license whatsoever. And I don't even think I can license words.
