### ISSUE TITLE
2 billion lines.

### ISSUE THREAD

**Issue by Katchowski** [kkrypt0nn/wordlists#54]
Hello, I would like to upload a wordlist to your repo but the file is far too large to upload. It is ~500mb (17gb uncompressed) compressed and contains over 2 billion lines (I don't know the exact amount as I don't have a way of opening the file to count them however if you need it I can probably do some math to figure it out). It contains every combination of [a - z] and [0 - 9] up to 6 characters, I likely would have done more if the size didn't jump straight to petabytes.

I created this abomination of a file in the first place because as far as I know there is no way to have hashcat try both letters and numbers for the same character place, it is either ?l or ?d (please correct me if you know this is wrong).

If you have a way of handling large wordlists such as this one I would love to add it to this repo.

**Comment by kkrypt0nn** [comment]
Hey there,

To be fair no idea, files are locked at 100MB on GitHub, files that go over them are to be stored in the LFS (Large File System if I remember correctly) of GitHub.

I wanted myself to do such a big wordlist, but uploading it on GitHub doesn't seem feasible.

If you stumble upon someone or you find something similar somewhere else, feel free to share your findings ^^

**Comment by Katchowski** [comment]
Went ahead and looked into this, trying on getting LFS working now. Once I get it working ill make a pull request.

**Comment by kkrypt0nn** [comment]
The issue is that it will be stored in my LFS, and I won't accept any PR that uses the storage of my LFS.
There's a storage limit of 1 GB if you don't pay, and I don't feel like paying for extra storage.
