### ISSUE TITLE
Docker image that contains the word list

### ISSUE THREAD

**Issue by trajano** [kkrypt0nn/wordlists#56]
Have a docker image containing only the word lists built and pushed when there's a change on the repo.

Something like

```Dockerfile
FROM scratch AS english
COPY wordlist/languages/english.txt /english.txt

FROM scratch AS languages
COPY wordlist/languages/*.txt /
```

**Comment by kkrypt0nn** [comment]
Hey there @trajano - sorry for the late response on that one, but I've added the docker build. Should be available via [`kkrypt0nn/wordlists:latest`](https://hub.docker.com/r/kkrypt0nn/wordlists) now :)
