### ISSUE TITLE
Negative Word List

### ISSUE THREAD

**Issue by FalsePhilosopher** [kkrypt0nn/wordlists#59]
I have a list of negative words that I sorted into a single line for scripting folder/file bombing here https://raw.githubusercontent.com/FalsePhilosopher/BadUSB-Playground/refs/heads/main/Misc/Negative_word_list.txt
I'm unsure of which folder I should PR it into, so let me know and I will throw a PR out.

**Comment by kkrypt0nn** [comment]
Thanks for the wordlist!

You can create a new category/folder with the name `miscellaneous`, it will also help for future wordlists.

I'd also name the file to something like `negative_words.txt`

**Comment by FalsePhilosopher** [comment]
> Thanks for the wordlist!
> 
> You can create a new category/folder with the name `miscellaneous`, it will also help for future wordlists.
> 
> I'd also name the file to something like `negative_words.txt`

👍 PR sent.
