### ISSUE TITLE
French profanity words

### ISSUE THREAD

**Issue by trajano** [kkrypt0nn/wordlists#65]
From: https://lingvist.com/course/learn-french-online/resources/french-curse-words/
https://french-iceberg.com/french-swear-words/
```
baiser
baltringue 
bête
bite
bordel
branleur
branleuse 
case
casse-toi
chatte 
chier
chieur 
chieuse 
con 
connard 
connasse 
conne
couilles
couillon
crétin 
crétine 
cueutard
cul	
degage
dégage
dieu
enculé
enculer
enfoiré 
fait
foutre
merde
mince
nique
niquer
niquer 
pétasse
pète 
putain
pute
sainte-mère
salaud
sale
salope 
saloppe
stupide
```

**Comment by kkrypt0nn** [comment]
Thanks for the proposal of a new wordlist!

Would you like to add it yourself or do you want me to add them myself?
if you wish to do it yourself please check out the contributing guidelines about file names, words ordering, etc.

If you find more words you may obviously add them as well.

**Comment by trajano** [comment]
French isn't my main language, I just had to disable the french wordlist for temporary password generation because of some words. :D

But I think it's best to keep them separate primarily because if you amalgamate all languages and filter out all the swear words world wide for a language, you may run out of words to use for password generation.

I would rather someone with actual French language experience to create an enhancement that relates to this.

**Comment by kkrypt0nn** [comment]
All right, will take a look at what I can do - thanks :D
